### ISSUE TITLE
还款可以为负数

### ISSUE THREAD

**Issue by Mr-Tim-CN** [wzytim/Bank#21]
![image](https://user-images.githubusercontent.com/53875091/83258849-99eb2d80-a1e9-11ea-840c-f2e4c330ce34.png)

**Comment by Mr-Tim-CN** [comment]
定期存款也可以草
![image](https://user-images.githubusercontent.com/53875091/83260485-74135800-a1ec-11ea-9675-9ac6872c1b20.png)

**Comment by iSudocat** [comment]
豚库逐渐充盈

**Comment by Mr-Tim-CN** [comment]
> 豚库逐渐充盈

？？？

**Comment by ExerciseBook** [comment]
草

**Comment by Mr-Tim-CN** [comment]
您怎么也来了艹




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric_Lian"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 晚上8:38
收件人: "wzytim/Bank"<Bank@noreply.github.com&gt;; 
抄送: "Tim"<690723857@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wzytim/Bank] 还款可以为负数 (#21)





 
草
 
&mdash;

**Comment by ExerciseBook** [comment]
邮件通知啊 @wzytim
