### ISSUE TITLE
外汇兑换后，回上级菜单，余额未更新

### ISSUE THREAD

**Issue by Mr-Tim-CN** [wzytim/Bank#35]
![image](https://user-images.githubusercontent.com/53875091/83320901-247d6c80-a27e-11ea-9d60-771e8ba578eb.png)

**Comment by JohnnyZhang728** [comment]
加1，我也发现了这个问题


![B`VVAYYC QF %T01T W{(G2](https://user-images.githubusercontent.com/58807422/83771361-c7861a00-a6b4-11ea-9891-84e3054b55a2.png)
