### ISSUE TITLE
报错的类型判断错误

### ISSUE THREAD

**Issue by Mr-Tim-CN** [wzytim/Bank#49]
![image](https://user-images.githubusercontent.com/53875091/84623348-aa054b80-af11-11ea-9ed4-966f41d5f89e.png)

**Comment by Mr-Tim-CN** [comment]
应该报：请选择币种

**Comment by Echo-kai** [comment]
这是因为你改了输入框。。。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wzytim"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 下午2:10
收件人:&nbsp;"wzytim/Bank"<Bank@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wzytim/Bank] 报错的类型判断错误 (#49)





 
应该报：请选择币种

**Comment by Mr-Tim-CN** [comment]
艹

**Comment by Mr-Tim-CN** [comment]
不对，我没改
![image](https://user-images.githubusercontent.com/53875091/84623756-8393e000-af12-11ea-8323-d60b03486428.png)
